#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Snapr\Console\StatsCommand;
use Snapr\Console\InternalCommand;

$application = new Application();
$application->add(new StatsCommand);
$application->add(new InternalCommand);
$application->run();